### ISSUE TITLE
www.teknofilo.com [Publicidad]

### ISSUE THREAD

**Issue by xDarkARG** [easylist/easylistspanish#13]
https://www.teknofilo.com/sony-anunciara-nuevos-smartphones-xperia-el-26-de-febrero/

**Comment by xDarkARG** [comment]
@diaux

**Comment by diaux** [comment]
Fixed. Commits below. Thanks for reporting!
9e66f149837fb5c907ac52c545f621a16c638fa3
57e1333a7f70d1a97d94af2f78e58d871743b7f5
