### ISSUE TITLE
www.puromarketing.com [Publicidad]

### ISSUE THREAD

**Issue by xDarkARG** [easylist/easylistspanish#14]
http://www.puromarketing.com/88/29758/percibimos-marcas-blancas-modo-diferente-nivel-subconsciente.html

**Comment by xDarkARG** [comment]
@diaux

**Comment by diaux** [comment]
Fixed. Commits below. Thanks for reporting!

0424d522f5c7aab71c966954dfaf1b98c2fea1f8
4beacb62226ddac201598d282d678f921ef72729
3081dfc1672ff2c6abb6efcbe88c74e843e7097f
d66d82ed02e5083b72b8303fd6e89e1777722e24
3f76e7550258da49132d3c437203869fb82b650f
6c0ae0b2f082c33a3b60bfb5e09e609a0a872f91
