### ISSUE TITLE
bernabeudigital.com/esfutbol.net/todoblaugrana.com

### ISSUE THREAD

**Issue by Khrin** [easylist/easylistspanish#153]
HI, I've encountered these three sites with some unblocked empty placeholders:

`https://www.bernabeudigital.com/`
`https://www.bernabeudigital.com/portada/i-isco-gana-enteros-para-ser-titular-en-el-partido-mas-importante-de-laliga-i-263454`

`https://www.esfutbol.net/`
`https://www.esfutbol.net/editorial-y-opinion/individualidades-que-hacen-equipo-75255`

`https://www.todoblaugrana.com/`
`https://www.todoblaugrana.com/primer-plano/ultima-hora-pique-tiene-un-esguince-en-el-ligamento-de-la-rodilla-derecha-63981`

**Comment by isacurad** [comment]
Thanks @Khrin. Filters added :thumbsup:
