### ISSUE TITLE
atresplayer.com

### ISSUE THREAD

**Issue by lain566** [easylist/easylistspanish#2]

**Comment by diaux** [comment]
I know you closed this Issue already, but just wanted to note that the filter you suggested back then
 ( @@||atresplayer.com^$generichide ) was indeed added to EasyList Spanish: https://github.com/easylist/easylistspanish/commit/2344fb7c2bf1a3df586c424522a5d7792f20fba3

**Comment by lain566** [comment]
@diaux Ok
Borre el mensaje, porque la regla fue añadido en otra lista de filtros.
