### ISSUE TITLE
ffcv.es

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylistspanish#295]
https://github.com/uBlockOrigin/uAssets/issues/16537#issuecomment-1407518788
https://github.com/uBlockOrigin/uAssets/issues/16537#issuecomment-1407701541

**Comment by garry-ut99** [comment]
Only some other ads have been hidden, but the white empty container is still here.

**Comment by garry-ut99** [comment]
@Khrin @Procyon-b , can we get any answer why the above placeholder not fixed

**Comment by Procyon-b** [comment]
It's up to Khrin to decide if the placeholders should be hidden by the SPA list
I've only proposed 2 filters that seem to work.

**Comment by garry-ut99** [comment]
I know, I was simply asking him for the reason, but well... he prefers an ignoring-atitude, a little rude, if I knew I wouldn't even ask, but that's the world we live in, so I'm not going to ask him anything anymore, no worth being ignored like a s... .

**Comment by garry-ut99** [comment]
It has been reported to AdGuard, we'll see whteher they fix it or not.
