### ISSUE TITLE
Story panel blocked on site

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylistspanish#305]
Site: vidaextra.com

Fixes (Caused by EasyList filters):
`@@||getjad.io/library/$script,domain=vidaextra.com`
`@@||getjad.io/prebid/$script,domain=vidaextra.com`
`@@||googleads.g.doubleclick.net/pagead/ads?$subdocument,domain=vidaextra.com`
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=vidaextra.com`

Fixes (Caused by EasyPrivacy filters):
`@@||googletagmanager.com^$script,domain=vidaextra.com`
`@@||mat.socy.es^$script,xhr,domain=vidaextra.com`
`@@||socy.es/pixel.json?$xhr,domain=vidaextra.com`
`@@||socy.es/pixel/js/$script,domain=vidaextra.com`

Screenshot 1 (Without filters): 
![Screenshot from 2023-03-30 15-36-38](https://user-images.githubusercontent.com/89158249/228945750-e45f82f0-9ea0-45ba-bc2d-586bfc80380d.png)

Screenshot 2 (With filters):
![Screenshot from 2023-03-30 15-37-08](https://user-images.githubusercontent.com/89158249/228945921-25cb85bc-7baf-4735-88f1-ef5ac214e61d.png)

**Comment by Sonic5435325** [comment]
@Khrin Story is still invisible after fix

**Comment by Khrin** [comment]
@Sonic5435325 Have you updated your filter lists?

**Comment by Sonic5435325** [comment]
Yes, two times

**Comment by Sonic5435325** [comment]
It only shows up if I allow all on the site, and still blocks it by default

**Comment by ryanbr** [comment]
Without EL Spanish, just EL/EP the site loads  as per screenshots.
