### ISSUE TITLE
radioagricultura.cl

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylistspanish#311]
URL: https://www.radioagricultura.cl/

On the site, there's an ad placeholder which blocks the entire site. 
![Screenshot from 2023-04-24 12-48-18](https://user-images.githubusercontent.com/89158249/234063580-4b36f431-62e2-4290-a18c-cd63e322a50e.png)

Some filters that can be used:
`||radioagricultura.cl/wp-content/plugins/welcome-ad-1/`
`radioagricultura.cl###welcome-ad`
`radioagricultura.cl##body:style(overflow: auto !important;)`

The last 2 filters are in AdGuard Spanish/Portugese, but the first isn't.

**Comment by Khrin** [comment]
Last filter is not supported.
