### ISSUE TITLE
tn.com.ar

### ISSUE THREAD

**Issue by apricotbucket28** [easylist/easylistspanish#313]
Page: `https://tn.com.ar/deportes/futbol/2023/05/02/lionel-scaloni-hablo-del-futuro-de-lionel-messi-y-dejo-una-frase-sorprendente-lo-ve-afuera-del-psg/`

The video is missing and unplayable with EL + EL Spanish + EP.
Possible solution: `@@||player.vodgc.net/dist/V3/genoa-event-tracking.min.js$domain=tn.com.ar`

**Comment by apricotbucket28** [comment]
@Khrin I can confirm that even after updating my filters, the video is still invisible.
Disabling EasyPrivacy or adding the filter `@@||player.vodgc.net/dist/V3/genoa-event-tracking.min.js^$script,domain=tn.com.ar` fixes the issue.

**Comment by Khrin** [comment]
@apricotbucket28 The filter was already listed in EasyPrivacy but was inadvertently removed, and I didn't noticed it. Now has been added again in EP and should be available in a few hours. Sorry for that.
