### ISSUE TITLE
20minutos.es

### ISSUE THREAD

**Issue by samueldiethelm** [easylist/easylistspanish#320]
Cookie banner shows up and scrolling is disabled

<img width="1072" alt="image" src="https://github.com/easylist/easylistspanish/assets/1754569/dff8e4dc-3548-4521-9b61-1b70edc8966c">

**Comment by Khrin** [comment]
This is not the right place to ask about problems with EasyList Cookies. You should have asked for it here: https://github.com/easylist/easylist

Either way, it cannot be blocked on this specific site.
