### ISSUE TITLE
audiotools.in

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylistspanish#323]
Ad placeholders:
`audiotools.in###custom_html-3`
`audiotools.in###custom_html-4`
`audiotools.in###custom_html-5`
`audiotools.in###custom_html-6`
`audiotools.in###custom_html-11`
![239428399-94b2bfc8-e3c0-4778-b940-e60621c0f13a](https://github.com/easylist/easylistspanish/assets/89158249/a0aec1a5-aa8e-4e7a-8f77-9f453f2091f2)

**Comment by Khrin** [comment]
This doesn't seem to be worth addressing at all, neither here nor elsewhere.
