### ISSUE TITLE
https://www.mitele.es/directo

### ISSUE THREAD

**Issue by Albert456** [easylist/easylistspanish#44]
The direct one does not work, I am examining.
https://mdsrwdassets-a.akamaihd.net/nsWGF/defaultview/5WI8A/fuckadblock.js
https://mdsrwdassets-a.akamaihd.net/defaultview/adjs.js
https://mdsrwdassets-a.akamaihd.net/favicon.ico
I think akamaihd would be the server.

**Comment by KiLL4FuNK** [comment]
use @Albert456

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4
