### ISSUE TITLE
megawarez.org | Move from EasyList

### ISSUE THREAD

**Issue by MS-PC** [easylist/easylistspanish#54]
@ryanbr, @diaux
They could move since it is a website in Spanish. Commit [166a3af](https://github.com/easylist/easylist/commit/166a3af0943492d121d5a628028c96205201b530)

**Comment by ryanbr** [comment]
Only reason I considered it was because the content, a non-spanish person downloading this "warez" wouldn't be out of character. but I dont mind removing if needs be.

**Comment by MS-PC** [comment]
@ryanbr I agree with your answer, I decline and close this issue.
