### ISSUE TITLE
https://ddmix.net/ [Publicidad]

### ISSUE THREAD

**Issue by xDarkARG** [easylist/easylistspanish#9]
https://ddmix.net/

**Comment by xDarkARG** [comment]
@diaux

**Comment by diaux** [comment]
Fixed. Commits below. Thanks for reporting!
b90049a110e1fc6db8f86e78190891674a792875
74a93c19adc70aa3385476e151559910720c1665
fe0ce2ceec684ae6148ad99fa66ac9c58dd3114f
8d1fd0263e03d6ff97299564d6b813a9b7dd8765
