### ISSUE TITLE
paginasiete.bo audio ads 

### ISSUE THREAD

**Issue by magicalthaw** [easylist/easylistspanish#91]
`https://www.paginasiete.bo/sociedad/2020/5/7/la-historia-del-asambleista-que-violo-abuso-de-ninos-254757.html`

there is an audio that don't allow me read properly any fix please in think this is from `playoncenter.com`

**Comment by magicalthaw** [comment]
@jabonsolo i deleted that issue form lanik, that's why i posted here, previously i posted on ublock origin but they told me that i must post here for spanish websites

**Comment by jabonsolo** [comment]
@magicalthaw, as mentioned in ublock comments, this is an annoyance not an ad. So when added to the list you would need to add [Fanboy's Annoyance List](https://easylist.to/easylist/fanboy-annoyance.txt) to your lists.
Created a pull request with the change.
https://github.com/easylist/easylist/pull/5328

**Comment by magicalthaw** [comment]
thanks for that

**Comment by jabonsolo** [comment]
Hola @magicalthaw, change was merged, sorry for it to take so long. Also I would like to encourage you to keep posting issues on Lanik forum, Spanish forum haven't been very well maintained during the last months but there is a new filter list author that I hope will keep a better track on it than I did.
